<!-- Comentario del for -->
<for var="arrDias" index="i" >
    <ul>
        <for var="arrDias.i" index="j">
            <li>{{arrDias.i.j}}</li>
        </for>
    </ul>
</for> 

<for var="arrUsuario" index="i">
    <h3>{{arrUsuario.i}} al reves</h3>
    <for var="arrUsuario.i" index="j" offset="+1" order="asc">
        <p>La pozicion <b>{{j}}</b> es la letra <b>{{arrUsuario.i.j}}</b> de la palabra <i>{{arrUsuario.i}}</i></p>
    </for>
</for>

<for index="i.0" size="10" offset="+1">
    <p>{{i}}</p>
</for>

<for index="i.a" size="ah" order="desc">
    <p>{{i}}</p>
</for> 


