<!-- Comentario del for -->
<for var="arrUsuario" index="i.0">
    <p>var.i                 ___ <b>{{arrUsuario.i}}</b></p>
    <p>var.i.xxx.etc         ___ <b>{{arrUsuario.i.otracosa}}</b></p>
    <p>i                     ___ <b>{{i}}</b></p>
    <p>var=var.i             ___ <b>var="arrUsuario.i"</b></p>
    <p>var=var.i.xxx.etc     ___ <b>var="arrUsuario.i.otracosa"</b></p>
    <p>var=i                 ___ <b>var="i"</b></p>
    <hr>
</for>



<for var="arrUsuario" index="i.0">
    <h5>Iterrando la palabra <b>{{arrUsuario.i}}</b></h5>
    <for var="arrUsuario.i" index="j.0">
        <p>La letra <b>{{arrUsuario.i.j}}</b> esta en la pozilion <b>{{j}}</b></p>
    </for>
</for>


<for var="arrDias" index="i.0">
    <ul>
        <for var="arrDias.i" index="j.0">
            <li>{{arrDias.i.j}}</li>
        </for>
    </ul>
</for>


<p>
    <for index="i.0" size="10" offset="+1">
        {{i}} 
    </for>
</p>

<p>
    <for index="i.0" size="10" offset="+1" order="desc">
        {{i}} 
    </for>
</p>


