<!-- Comentario del for -->
<for var="arrUsuario" index="i.0">
    <p>var.i                 ___ <b>{{arrUsuario.i}}</b></p>
    <p>var.i.xxx.etc         ___ <b>{{arrUsuario.i.otracosa}}</b></p>
    <p>i                     ___ <b>{{i}}</b></p>
    <p>var=var.i             ___ <b>var="arrUsuario.i"</b></p>
    <p>var=var.i.xxx.etc     ___ <b>var="arrUsuario.i.otracosa"</b></p>
    <p>var=i                 ___ <b>var="i"</b></p>
    <hr>
</for>


<for var="arrUsuario" index="i.0">
    <ul>
      
            <li>{{arrUsuario.i}}</li>
      
    </ul>
</for>
