<!-- Este comentario configurable eliminacion -->
<if var="edad" cond="1">
    <p>Contenido del bloque <b>if</b></p>
</if>
<!-- este comentario se eliminara -->
<elseif var="nombre" cond="">
    <p>Contenido del bloque <b>elseif 1</b></p>
</elseif>
<!-- este comentario se eliminara -->
<elseif var="edad">
    <p>Contenido del bloque <b>elseif 2</b></p>
</elseif>
<!-- este comentario se eliminara --->
<else>
    <p>Contenido del bloque <b>else</b></p>
</else>
