<!-- Comentario antes del switch -->
<switch var="edad">
    <!-- Comentario antes del case -->
    <case cond="">
        <p>Contenido del <b>case 1</b></p>
    </case>
    <!-- Comentario antes del case -->
    <case cond="">
        <p>Contenido del <b>case 2</b></p>
    </case>
    <!-- Comentario antes del case -->
    <default>
        <p>Contenido del <b>default</b></p>
    </default>
</switch>