<p>Ejemplo de imprimir variables con <b>PHTML</b></p>
<p> El valor de la variable en minusculas es <b>{{lower.nombre}}</b>
<p> El valor de la variable en mayusculas es <b>{{upper.nombre}}</b>
<p>Mostrar funcion de formatear propia <a href="{{crear_enlace.enlace}}">{{crear_enlace.enlace}}</a></p>
<p>La variable SERVER LOCAL ADDR es <b>{{_SERVER.LOCAL_ADDR}}</b>
<p>La variable SERVER REMOTE ADDR es <b>{{_SERVER.REMOTE_ADDR}}</b>
<p> El valor de la variable en mayusculas es <b>{{camelcase.nombre}}</b>
